--[[
"merger.new_buffer_source"
"merger.new_tuple_source"
"merger.new"
"merger.new_source_fromtable"
"merger.new_source_frombuffer"
"merger.internal"
"merger.select"
"merger.ipairs"
"merger.new_table_source"
]]
